---
title: ""
output: html_notebook
---


### A Notebook for creating presentation visuals

```{r}
# imports
library(ggplot2)
library(sysfonts)

library(tidyverse)
library(extrafont)
library(cowplot)

font_add_google("Barlow Semi Condensed")

font_import()
```



```{r}
d = data.frame(f1 = c(.38, .51, .56, .62, .64), t = 1:5)
p <- ggplot(data = d, aes(x=t, y=f1)) +
  geom_line(color='skyblue3') +
  geom_point(color='skyblue3') +
  ylim(.35, .67) +
  geom_text(aes(label=f1), hjust=0.2, vjust=2)
  
p
  
```

```{r}
d <- data.frame(
  percentage = c('0-25%', '25-50%', '50-75%', '75-100%'),
  portion = c(18,33,40,9),
  class = c(0,0,1,0)
  )

ggplot(d, aes(x=percentage, y=portion)) +
  geom_bar(stat='identity', color="NA", fill=c("grey68", "grey68", "skyblue3", "grey68")) +
  geom_text(aes(label = paste0(d$portion,"%")), color = "white", position="identity", hjust = 1.1, size=10, family = "Barlow Semi Condensed") +
  coord_flip() +
  theme(
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill="#F3F3F3", linetype="blank"))
```






